version: '3.1'
services:
  #NGINX Proxy Server
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      #- 443:443
    restart: on-failure:3
  #Nextjs APP
  react-app:
    image: react-app
    build: 
      context:  ./client/
      dockerfile:  Dockerfile
    stdin_open: true
    volumes: 
      - ./client:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure:3
    command: npm run dev
  #API Service
  api-server:
    image: api-servers
    build: 
      context:  ./server/
      dockerfile:  Dockerfile
    volumes: 
      - ./server:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure:3
    command: npm run dev
    depends_on:
      - mongo
  #mongo db database
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure:3
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - database:/data/db
  # Mongo Express DB Ui
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure:3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
volumes:
  database: {}
networks: 
  Tickbid-webapp:
    name: Tickbid-webapp
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
