# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev-production" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        
      - name: script
        run: |
          docker-compose up -d
          docker login -u httpsdom -p dckr_pat_9XGuNVW0bHzsU7UKTHk9hZgc_z4
          
          docker tag ExpressAPI httpsdom/tickbid:ExpressAPI
          docker push httpsdom/tickbid:ExpressAPI

          docker tag FastifyAPIt httpsdom/tickbid:FastifyAPI
          docker push httpsdom/tickbid:FastifyAPI

          docker tag ws-socket httpsdom/tickbid:WebSocket
          docker push httpsdom/tickbid:WebSocket
